[0m22:22:10.071047 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194092FBE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001940A6E3D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001940A6E3890>]}


============================== 22:22:10.074514 | affd6b09-b53c-4efa-9302-b91caa6ee0fa ==============================
[0m22:22:10.074514 [info ] [MainThread]: Running with dbt=1.10.4
[0m22:22:10.075079 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\PC\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init dbt_inicio', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:22:10.090866 [debug] [MainThread]: Starter project path: C:\Users\PC\OneDrive\Documentos\dbt_ecommerce\.venv\Lib\site-packages\dbt\include\starter_project
[0m22:22:10.111640 [info ] [MainThread]: 
Your new dbt project "dbt_inicio" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:22:10.112197 [info ] [MainThread]: Setting up your profile.
[0m22:23:22.285278 [info ] [MainThread]: Profile dbt_inicio written to C:\Users\PC\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:23:22.286296 [debug] [MainThread]: Command `dbt init` succeeded at 22:23:22.286198 after 72.32 seconds
[0m22:23:22.286569 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001940B6DFCE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001940B78F9B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001940A586030>]}
[0m22:23:22.286865 [debug] [MainThread]: Flushing usage events
[0m22:23:22.986559 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:27:18.708028 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E311577E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E312953D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E312953890>]}


============================== 22:27:18.711756 | 5eaa4523-7461-43c4-89f4-6c6a7f7af80c ==============================
[0m22:27:18.711756 [info ] [MainThread]: Running with dbt=1.10.4
[0m22:27:18.712316 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\PC\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:27:18.727473 [info ] [MainThread]: dbt version: 1.10.4
[0m22:27:18.727859 [info ] [MainThread]: python version: 3.13.1
[0m22:27:18.728237 [info ] [MainThread]: python path: C:\Users\PC\OneDrive\Documentos\dbt_ecommerce\.venv\Scripts\python.exe
[0m22:27:18.728627 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m22:27:18.774463 [info ] [MainThread]: Using profiles dir at C:\Users\PC\.dbt
[0m22:27:18.774923 [info ] [MainThread]: Using profiles.yml file at C:\Users\PC\.dbt\profiles.yml
[0m22:27:18.775292 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\PC\OneDrive\Documentos\dbt_ecommerce\dbt_project.yml
[0m22:27:18.776278 [info ] [MainThread]: adapter type: postgres
[0m22:27:18.776587 [info ] [MainThread]: adapter version: 1.9.0
[0m22:27:18.776897 [info ] [MainThread]: Configuration:
[0m22:27:18.777171 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m22:27:18.777443 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m22:27:18.777708 [info ] [MainThread]: Required dependencies:
[0m22:27:18.778013 [debug] [MainThread]: Executing "git --help"
[0m22:27:18.783002 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m22:27:18.783342 [info ] [MainThread]: Connection:
[0m22:27:18.783711 [info ] [MainThread]:   host: localhost
[0m22:27:18.784028 [info ] [MainThread]:   port: 5432
[0m22:27:18.784334 [info ] [MainThread]:   user: postgres
[0m22:27:18.784666 [info ] [MainThread]:   database: dbt_pg
[0m22:27:18.785000 [info ] [MainThread]:   schema: dbt_db
[0m22:27:18.785290 [info ] [MainThread]:   connect_timeout: 10
[0m22:27:18.785570 [info ] [MainThread]:   role: None
[0m22:27:18.785856 [info ] [MainThread]:   search_path: None
[0m22:27:18.786121 [info ] [MainThread]:   keepalives_idle: 0
[0m22:27:18.786420 [info ] [MainThread]:   sslmode: None
[0m22:27:18.786674 [info ] [MainThread]:   sslcert: None
[0m22:27:18.786942 [info ] [MainThread]:   sslkey: None
[0m22:27:18.787188 [info ] [MainThread]:   sslrootcert: None
[0m22:27:18.787437 [info ] [MainThread]:   application_name: dbt
[0m22:27:18.787686 [info ] [MainThread]:   retries: 1
[0m22:27:18.788203 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m22:27:19.010600 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m22:27:20.512235 [debug] [MainThread]: Using postgres connection "debug"
[0m22:27:20.512561 [debug] [MainThread]: On debug: select 1 as id
[0m22:27:20.512775 [debug] [MainThread]: Opening a new connection, currently in state init
[0m22:27:20.525943 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "dbt_pg" does not exist

[0m22:27:20.533797 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m22:27:20.534203 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m22:27:20.534474 [debug] [MainThread]: On debug: No close available on handle
[0m22:27:20.534706 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m22:27:20.535103 [info ] [MainThread]: [31m3 checks failed:[0m
[0m22:27:20.535453 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\PC\OneDrive\Documentos\dbt_ecommerce\dbt_project.yml> not found

[0m22:27:20.535786 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m22:27:20.536093 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "dbt_pg" does not exist
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m22:27:20.537057 [debug] [MainThread]: Command `dbt debug` failed at 22:27:20.536963 after 1.93 seconds
[0m22:27:20.537306 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m22:27:20.537551 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E313BEE060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E313BF30B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E313A25150>]}
[0m22:27:20.537840 [debug] [MainThread]: Flushing usage events
[0m22:27:21.225261 [debug] [MainThread]: An error was encountered while trying to flush usage events
